SET CURRENT SCHEMA MMGM;

CREATE TABLE
    MMGM.TBL_MMGM_REJECT_REASON
    ( 
        REASON_ID CHARACTER(32) WITH DEFAULT NOT NULL,
        TASK_ID CHARACTER(32) WITH DEFAULT NOT NULL, 
        REASON_TP CHARACTER(4) WITH DEFAULT NOT NULL,
        REASON_MEMO VARCHAR(1024) WITH DEFAULT NOT NULL,
        REC_ST CHARACTER(1) WITH DEFAULT NOT NULL,
        COMMENTS VARCHAR(160) WITH DEFAULT NOT NULL,
        REC_CRT_TS TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
        REC_UPD_TS TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL, 
        CONSTRAINT IND_MMGM_RR_PK PRIMARY KEY (REASON_ID)
    );

GRANT ALL ON MMGM.TBL_MMGM_REJECT_REASON TO USER OP_MGMAP;
GRANT SELECT ON MMGM.TBL_MMGM_REJECT_REASON TO USER OP_MGMMN;
