SET CURRENT SCHEMA ARGS;

CREATE TABLE
    ARGS.TBL_ARGS_REASON_TYPE
 (   
     REASON_TP CHARACTER(4) WITH DEFAULT NOT NULL,   
     REASON_MEMO VARCHAR(64) WITH DEFAULT NOT NULL,  
     REC_ST CHARACTER(1) WITH DEFAULT NOT NULL,
     IS_COMMON CHARACTER(1) WITH DEFAULT NOT NULL,
     COMMENTS VARCHAR(160) DEFAULT '' NOT NULL,
     REC_CRT_TS TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
     REC_UPD_TS TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL, 
     CONSTRAINT IND_MMGM_RT_PK PRIMARY KEY (REASON_TP)
 );

GRANT ALL ON ARGS.TBL_ARGS_REASON_TYPE TO USER OP_MGMAP;
GRANT SELECT ON ARGS.TBL_ARGS_REASON_TYPE TO USER OP_MGMMN;
